theme: osuny
_merge: deep
params:
  plausible: senrgies.fr
  summary:
    position: hero
  logo:
    header: '/assets/images/logo-SEnRgies-white.svg'
    footer: '/assets/images/logo-SEnRgies-color.svg'
    
  image_sizes:
    sections:
      home:
        hero:
          desktop:  1920
