theme: osuny
_merge: deep
params:
  summary:
    position: hero
  search:
    active: true
  logo:
    header: '/assets/images/logo-SEnRgies-white.svg'
    footer: '/assets/images/logo-SEnRgies-color.svg'